export const EVENT_REGISTER_NAME_MAX_LENGTH = 12;

export {
  WOW_BLOODLUST_CLASSES as EVENT_REGISTER_BLOODLUST_CLASSES,
  WOW_BATTLEREZ_CLASSES as EVENT_REGISTER_BATTLEREZ_CLASSES,
} from '@/constants/wowRaidBuffClasses';
